# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/languages/python/
language: python

python:
    - "3.6"

install:
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.42.2/hugo_0.42.2_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf blog
    - ls
    - pwd

script:
    - hugo -d blog --themesDir myTheme
    - echo 'Hugo build done!'
after_success:
    - git config --global user.email "allenforuse@gmail.com"
    - git config --global user.name "justforuse"
    - git clone --recursive https://$GITHUB_TOKEN@github.com/justforuse/justforuse.github.io.git container
    - rm -rf container/blog
    - cp -r blog container 
    - cd container
    - ls
    - git add .
    - git commit -m 'Travis upate blog'
    - git push -u origin master